# This is a basic workflow to help you get started with Actions

name: Clean empty MD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
#       # Runs a set of commands using the runners shell
#       - name: Удаление пустых md-файлов
#         run: |
#           for var in $(ls)
#             do
#                 txt=$(cat $var)
#                 if [[ "${txt//"
#                 "/"."}" == "" ]]; then

#                 if [[ "$var" == *.md ]]; then
#                     echo "Удаление:" $var
#                     rm $var
#                 fi
#                 fi
#             done
        
          
#       - name: Commit файлов
#         run: |
#           status=$(git status)
#           if [[ "$status" != *"nothing to commit"* ]]; then
#             git config --global user.email "ilapro53@gmail.com"
#             git config --global user.name "github actions"
#             git add .
#             git commit -m "Удалены пустые md-файлы"
#             git push
#             echo "Commit выполнен"
#           fi
          
#           if [[ "$status" == *"nothing to commit"* ]]; then
#             echo "Файлы не изменены. Commit не требуется"
#           fi

      - name: Commit файлов
        run: |
          python3
